### ISSUE TITLE
File or folder does not exist

### ISSUE THREAD

**Issue by lm913** [coderaiser/es-require#1]
Thank you for presenting this as a solution for 'require()' I'm running into an issue with it though here is my folder structure:

src
| --- test.js
| --- lib
| --- | --- require.js
| --- | --- testLib.js

**test.js**
```javascript
#include "lib/require.js";
var testLib_1 = require("testLib");

function main() {
    testLib_1["default"]();
}

main();
```

**testLib.js**
```javascript
function mang() {
    $.writeln("here");
}

exports["default"] = mang;
```

The error I'm receiving in ESTK is that it does not recognize the file passed into `require()` (in this example _'testLib'_) as a valid location

**Comment by coderaiser** [comment]
Looks like you should add prefix `./` to name:

```js
var testLib_1 = require("./testLib");
```

**Comment by lm913** [comment]
I've tried the following:

```javascript
var testLib_1 = require("testLib");
var testLib_1 = require("/testLib");
var testLib_1 = require("./testLib");
var testLib_1 = require("./lib/testLib");
```

the first three result in _'File or folder does not exist_' and the last one (as expected) results in an _'I/O error'_

Do you happen to have a working example project that I could look at to see if I'm missing something?

I can make adjustments to the require.js file to add the missing path information but it's relative to the script's location. Ideally I could have it live in a common folder accessible by any script. Specifically the changes I made to get it working were:

```javascript
file = new File(File($.fileName).parent.path + "/" + name + ext);
// file = new File(name + ext); 
```

Thanks!
Dave

**Comment by coderaiser** [comment]
I think you should add [require.dir](https://github.com/coderaiser/es-require/blob/master/lib/require.js#L61) to make things working:

```js
require.dir('./');
var testLib_1 = require("./testLib");
```

I wrote this script long time ago, and I do not have `Adobe After Effect` right now. If you have ideas for improvements you are welcome :). What I have from that time is [es-node](https://github.com/coderaiser/es-node) only.

**Comment by lm913** [comment]
Ah, I wonder if this issue is because After Effects and Photoshop handle paths differently. Thanks for your help in this! I'll look into it a bit more

**Comment by coderaiser** [comment]
I do not think they handle paths differently. What version of Photoshop do you use?

**Comment by lm913** [comment]
You're right they don't. I've never used After Effects in ESTK, but I did figure out how to get it working for me :)

**test.js**
```javascript
"use strict";
#include "./common/require.js";
require.dir(File($.fileName).path + "/lib/");
var testLib_1 = require("./testLib");
function main() {
    testLib_1["default"]();
}
main();
```

***testLib.js***
```javascript
"use strict";
function mang() {
    $.writeln("hello");
}
exports["default"] = mang;
```

and I modified your _require.js_ to `return exports` instead of `module.exports` because I'm transpiling to ES3 from Typescript commonjs which uses `exports` instead of `module.exports`
